openapi: 3.0.0
info:
  title: Telegram Bot API
  description: API для Telegram-бота планировщика событий
  version: 1.0.0
  contact:
    name: ira
    email: irakoch23@yandex.ru
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /:
    get:
      tags:
        - Health
      summary: Проверка статуса работоспособности
      description: Возвращает статус работоспособности Telegram-бота
      responses:
        '200':
          description: Бот работает корректно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /health:
    get:
      tags:
        - Health
      summary: Проверка статуса
      description: Возвращает детальную информацию о состоянии сервиса
      responses:
        '200':
          description: Сервер работает корректно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedHealthResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          example: "healthy"
          description: Статус работоспособности
        message:
          type: string
          example: "Telegram bot is running"
          description: Сообщение о состоянии
      description: Ответ от эндпоинта проверки статуса
    DetailedHealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: "ok"
          description: Детальный статус работоспособности
      description: Ответ от эндпоинта детальной проверки статуса
    Error:
      type: object
      required:
        - status
        - error
      properties:
        status:
          type: string
          example: "error"
          description: Статус ошибки
        error:
          type: string
          example: "Internal server error"
          description: Описание ошибки
      description: Ответ при ошибке
tags:
  - name: Health
    description: Методы проверки работоспособности сервиса
