openapi: 3.0.0
info:
  title: AI Diet Bot API
  description: REST API для AI Diet Bot 3.0
  version: 1.0.0

servers:
  - url: https://ai-diet-bot-snevezhin.amvera.io/api
    description: Production server (Amvera)
  - url: http://0.0.0.0:8080/api
    description: Development server

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"

  /users:
    post:
      summary: Create new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                telegram_id:
                  type: integer
                name:
                  type: string
      responses:
        '201':
          description: User created
        '400':
          description: Bad request

  /users/{telegram_id}:
    get:
      summary: Get user by Telegram ID
      parameters:
        - name: telegram_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User data
        '404':
          description: User not found

  /meal-plans:
    post:
      summary: Generate meal plan
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                telegram_id:
                  type: integer
      responses:
        '201':
          description: Meal plan generated
        '400':
          description: Bad request

components:
  schemas:
    User:
      type: object
      properties:
        athlete_id:
          type: integer
        telegram_id:
          type: integer
        name:
          type: string

    MealPlan:
      type: object
      properties:
        plan_id:
          type: integer
        plan_name:
          type: string
        total_calories:
          type: number